const Patients = [
  {
    id: 1,
    firstname: "Kelvin",
    lastname: "Samson",
    email: "Melvin@sample.com",
    phone: "0615487985",
    lastAppointment: "2020-05-20",
    atRisk: true,
    name: "DRCarlton",
    room: "Kelvin-Samson",
  },
  {
    id: 2,
    firstname: "Annabel",
    lastname: "Stone",
    email: "Annabel@sample.com",
    phone: "0615487987",
    lastAppointment: "2020-05-22",
    atRisk: true,
    name: "DRCarlton",
    room: "Annabel-Stone",
  },
  {
    id: 3,
    firstname: "Grace",
    lastname: "Loveday",
    email: "Grace@sample.com",
    phone: "0615487147",
    lastAppointment: "2020-05-24",
    atRisk: false,
    name: "DRCarlton",
    room: "Grace-Loveday",
  },
  {
    id: 4,
    firstname: "Angela",
    lastname: "Gonzales",
    email: "Angela@sample.com",
    phone: "0615487963",
    lastAppointment: "2020-06-20",
    atRisk: true,
    name: "DRCarlton",
    room: "Angela-Gonzales",
  },
  {
    id: 5,
    firstname: "Paulo",
    lastname: "Avent",
    email: "Paulo@sample.com",
    phone: "0615487851",
    lastAppointment: "2020-06-27",
    atRisk: false,
    name: "DRCarlton",
    room: "Paulo-Avent",
  },
  {
    id: 6,
    firstname: "Olivia",
    lastname: "Clint",
    email: "Oliva@sample.com",
    phone: "0615487851",
    lastAppointment: "2020-04-27",
    atRisk: false,
    name: "DRCarlton",
    room: "Olivia-Clint",
  },
  {
    id: 7,
    firstname: "Dylan",
    lastname: "Bristoll",
    email: "Dylan@sample.com",
    phone: "0615487851",
    lastAppointment: "2020-03-12",
    atRisk: false,
    name: "DRCarlton",
    room: "Dylan-Bristoll",
  },
  {
    id: 8,
    firstname: "Thomas",
    lastname: "Prime",
    email: "thomas@sample.com",
    phone: "0615487851",
    lastAppointment: "2020-06-11",
    atRisk: false,
    name: "DRCarlton",
    room: "Thomas-Prime",
  },
  {
    id: 9,
    firstname: "Eve",
    lastname: "Wen",
    email: "Eve@sample.com",
    phone: "0615487851",
    lastAppointment: "2020-01-11",
    atRisk: true,
    name: "DRCarlton",
    room: "Eve-Wen",
  },
];
export default Patients;
