const Patients = [
  {
    id: 1,
    firstname: "Kelvin",
    lastname: "Samson",
    email: "Melvin@sample.com",
    phone: "0615487985",
    lastAppointment: "2020-05-20",
    atRisk: true,
    name: "DRCarlton",
    room: "Kelvin-Samson",
  },
  {
    id: 2,
    firstname: "Annabel",
    lastname: "Stone",
    email: "Annabel@sample.com",
    phone: "0615487987",
    lastAppointment: "2020-05-22",
    atRisk: true,
    name: "DRCarlton",
    room: "Annabel-Stone",
  },
  {
    id: 3,
    firstname: "Grace",
    lastname: "Loveday",
    email: "Grace@sample.com",
    phone: "0615487147",
    lastAppointment: "2020-05-24",
    atRisk: false,
    name: "DRCarlton",
    room: "Grace-Loveday",
  },
  {
    id: 4,
    firstname: "Angela",
    lastname: "Gonzales",
    email: "Angela@sample.com",
    phone: "0615487963",
    lastAppointment: "2020-06-20",
    atRisk: true,
    name: "DRCarlton",
    room: "Angela-Gonzales",
  },
  {
    id: 5,
    firstname: "Paulo",
    lastname: "Avent",
    email: "Paulo@sample.com",
    phone: "0615487851",
    lastAppointment: "2020-06-27",
    atRisk: false,
    name: "DRCarlton",
    room: "Paulo-Avent",
  },
];
export default Patients;
